### ISSUE TITLE
HTTP Links Not Working

### ISSUE THREAD

**Issue by Lord0fBytes** [casualwriter/casual-markdown#1]
I was playing around with this and it doesn't appear that `http` links are being detected with the javascript. 
I think the syntax for the javascript  regex should be the following:

Current: 
`mdstr = mdstr.replace(/([<\s])(http[s]\:\/\/.*?)([\s\>])/gm, '$1<a href="$2">$2</a>$3')`

Proposed:
used a `?` behind the `s` in `https`
`mdstr = mdstr.replace(/([<\s])(https?\:\/\/.*?)([\s\>])/gm, '$1<a href="$2">$2</a>$3')`

Seems to work now. 

Edit this is where I am referring to: https://github.com/casualwriter/casual-markdown/blob/1a5640b2dbbae18d01eebbb98f6c76ca354a4cc8/source/casual-markdown.js#L88

**Comment by casualwriter** [comment]
thanks. u r right. i will update repo asap.
